video:
  width: 480
  height: 320
  fbdev: fb1
  driver: x11

audio:
  enabled: True
  oscilloscope_factor: 2 # Mostly meaningless, just tweak to your liking.

map:
  latitude: 38.9670302
  longitude: -77.2502904

key_bindings:
  'F1': 'module_stats'
  'F2': 'module_items'
  'F3': 'module_data'
  '1': 'knob_1'
  '2': 'knob_2'
  '3': 'knob_3'
  '4': 'knob_4'
  '5': 'knob_5'
  'UP': 'dial_up'
  'DOWN': 'dial_down'

# Using GPIO.BCM as mode
gpio_bindings:
  4: 'module_stats'
  14: 'module_items'
  15: 'module_data'
  5: 'knob_1'
  18: 'knob_2'
  27: 'knob_3'
  13: 'knob_4'
  23: 'knob_5'
  6: 'dial_up'
  12: 'dial_down'

# Using GPIO.BCM as mode - assuming this is the same!
dial_gpio_bindings:
  'pin_a': 0
  'pin_b': 0

radio:
  stations:
    diamondcity:
      label: 'Diamond City Radio'
      directory: 'sounds/radio/dcr/'
    sanctuary:
      label: 'Minutemen Radio'
      directory: 'sounds/radio/sanctuary/'