video:
  width: 480
  height: 320

audio:
  enabled: True
  oscilloscope_factor: 2 # Mostly meaningless, just tweak to your liking.

map:
  latitude: -102.3016145
  longitude: 21.8841274

key_bindings:
  'F1': 'module_stats'
  'F2': 'module_items'
  'F3': 'module_data'
  '1': 'knob_1'
  '2': 'knob_2'
  '3': 'knob_3'
  '4': 'knob_4'
  '5': 'knob_5'
  'UP': 'dial_up'
  'DOWN': 'dial_down'

# Using GPIO.BCM as mode
gpio_bindings:
  4: 'module_stats'
  14: 'module_items'
  15: 'module_data'
  17: 'knob_1'
  18: 'knob_2'
  7: 'knob_3'
  22: 'knob_4'
  23: 'knob_5'
  31: 'dial_up'
  27: 'dial_down'
